version: "3.3"

services:

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=app_development

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
        - "mysql"
    ports:
      - 9999:80
    environment:
      - PMA_ARBITRARY=1
